name: Release AddOn

#on: [push]
on:
  push:
    tags:
      - '**'

jobs:
  standalone_release:
    runs-on: ubuntu-latest
    steps:
      - name: Install svn
        run: sudo apt-get install -y subversion

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: IsFairy/packager@v1.0.0
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
